version: "3.9"
services:
  hu-automation:
    build: .
    container_name: hu-automation-hu-automation-1
    ports:
      - "8080:5000"
    environment:
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
    env_file:
      - .env
    volumes:
      - ./:/app
    restart: unless-stopped